### ISSUE TITLE
Outlines do not have border radius in Safari

### ISSUE THREAD

**Issue by BlueSlug** [fluid-project/handbook.floeproject.org#109]
## Describe the bug

As detailed in [this WebKit bug report](https://bugs.webkit.org/show_bug.cgi?id=20807), Safari and other WebKit-based browsers do not correctly display rounded corners (`border-radius`) on CSS outlines.

This issue has been filed primarily to signal our awareness of the problem rather than as an intent to address it.

### To reproduce

1. Go to the Home page
2. Hover over or focus on the "Inclusive Design Research Centre" link at the top-left of the page
3. See error

### Expected behavior

The outline in the focus/hover style should have rounded corners.

## Screenshots

Actual behaviour:
![image](https://user-images.githubusercontent.com/547933/172901003-68152ce9-b541-4402-ac0f-ef7243a477bb.png)

Intended behaviour: 
![image](https://user-images.githubusercontent.com/547933/172901062-16bf6f79-40e8-4046-a248-d23ad6ecf3a5.png)

### Desktop

- OS: macOS 10.11.6 (El Capitan)
- Browser & version: Safari 11.1.2

### Mobile device

N/A

### Assistive technology used

N/A

## Additional context or notes

N/A

**Comment by greatislander** [comment]
The way I've handled this elsewhere uses box shadows instead of a styled outline. This works across all supported browsers. If you were to go this route, it is good practice to keep the outline and change it as follows:

```css
.some-element:focus {
	outline: 1px solid transparent;
}
```

This preserves the focus ring in Windows High Contrast Mode where box shadows are removed.

**Comment by greatislander** [comment]
This is resolved in Safari 17!
