### ISSUE TITLE
Implement the new design for the Inclusive Learning Design Handbook

### ISSUE THREAD

**Issue by jhung** [fluid-project/handbook.floeproject.org#46]
Implement the redesign to information architecture and visual design for the Inclusive Design Learning Handbook. The designs can be found here:

https://wiki.fluidproject.org/display/fluid/ILDH+Redesign

**Comment by jhung** [comment]
Using this space as a way to discuss a plan in how the redesign can be broken down into tasks or phases.

One possible approach is to look into implementing the new information architecture using the existing site first, then take on the visual redesign in a separate task.

Looking at [the proposed information architecture](https://wiki.fluidproject.org/display/fluid/ILDH+Redesign?preview=/182190509/182190518/ILDH_%20site%20flow_Aug20%2C%202019.pdf), some things are notable:
1. there is new content (like under "About") - does this content exist elsewhere or will it need to be written, and by whom?
2. the information architecture does not quite match the wireframe. For example in the IA, there is no landing page for the Techniques section, but in the wireframe [a landing page is shown](https://wiki.fluidproject.org/display/fluid/ILDH+Final+Design?preview=/197493280/197493266/Screen%20Shot%202020-06-08%20at%203.18.56%20PM.png).

Questions to have answered:
* Do all sections have landing pages?
* What are "Detail pages" as indicated in the IA?

**Comment by michelled** [comment]
Tasks remaining as of Feb 8 before a pull request will be made:

- Create the directory structure based on the content structure
- Update the i18n notes in the README once the dir structure settles down
- Check fluid-lint-all config to ensure all necessary files are being linted
- Double-check markdown [![Figure...](...)] bits
- Make sure CMS editor is working properly

**Comment by michelled** [comment]
The branch where this is being worked on: https://github.com/BlueSlug/handbook.floeproject.org/tree/feat/design-update-GH-46
