### ISSUE TITLE
Implement CSS polyfills for newer rules

### ISSUE THREAD

**Issue by BlueSlug** [fluid-project/handbook.floeproject.org#63]
## Is your feature request related to a problem?

Some styling rules use newer CSS specifications that may not be supported by older browsers/clients, in particular [CSS logical properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties).

## Describe the solution you'd like

Implement automatic polyfilling for logical CSS properties. The Floe Project site uses the [postcss-logical npm package](https://www.npmjs.com/package/postcss-logical) and [browserslist](https://github.com/browserslist/browserslist), though this may be tricky to integrate since the ILDH uses Sass as its CSS preprocessor.

## Describe alternative solutions you've considered

N/A

## Additional context or notes

N/A

**Comment by greatislander** [comment]
@BlueSlug FYI, Laravel Mix (which Trivet/this site uses) runs compiled CSS from Sass through PostCSS to apply vendor prefixes so this should be as straightforward as specifying the desired plugins in a config block in `webpack.mix.js` as shown here:

https://github.com/laravel-mix/laravel-mix/issues/439#issuecomment-335041311 ([reference](https://laravel-mix.com/docs/6.0/api#optionsoptions))

**Comment by greatislander** [comment]
Might look something like:

```js
mix.options({
  postCss: [
    require('postcss-logical')
  ]
});

**Comment by BlueSlug** [comment]
> @BlueSlug FYI, Laravel Mix (which Trivet/this site uses) runs compiled CSS from Sass through PostCSS to apply vendor prefixes so this should be as straightforward as specifying the desired plugins in a config block in `webpack.mix.js` as shown here:
> 
> [laravel-mix/laravel-mix#439 (comment)](https://github.com/laravel-mix/laravel-mix/issues/439#issuecomment-335041311) ([reference](https://laravel-mix.com/docs/6.0/api#optionsoptions))

@greatislander it's great to have confirmation of this and some config to refer to, thanks! :)

I was reasonably sure that, while I worked on the site redesign, I'd tried calling `mix.postCss( ... )` immediately after [the line that builds `main.css`](https://github.com/fluid-project/handbook.floeproject.org/blob/e600ce288154e613f3234605d57644b3d6cf0a0c/webpack.mix.js#L26), but I wasn't sure enough to know that or how this might jive with `postcss-logical`. I'm glad it's an easy solution!
